### ISSUE TITLE
docs not updating automatically?

### ISSUE THREAD

**Issue by initze** [awi-response/darts-nextgen#11]
https://awi-response.github.io/darts-nextgen/latest/ref/preprocessing/

it seems that the docs are not updating properly

![image](https://github.com/user-attachments/assets/485537ab-80b3-40f9-ad3b-12c7d526bfac)

**Comment by relativityhd** [comment]
They are only updating on release. To do a release go to [Actions](https://github.com/awi-response/darts-nextgen/actions) -> On the left "Update Version" -> In the blue field on "Run workflow" and select whether you want to do a patch, minor or major version dump.
