### ISSUE TITLE
Revisit dependencies

### ISSUE THREAD

**Issue by relativityhd** [awi-response/darts-nextgen#4]
Redo the dependency management. Potential considerations:

- uv has almost all features of rye needed for this repo, maybe we could switch?
- does a workspace setup make still sense? Is it worth the effort to have each package has its own set of dependencies, or would it be better to flatten them out to the top-level?

**Comment by initze** [comment]
> does a workspace setup make still sense? Is it worth the effort to have each package has its own set of dependencies, or would it be better to flatten them out to the top-level?

I would prefer to flatten as long as we don't have conflicts between modules

**Comment by initze** [comment]
> uv has almost all features of rye needed for this repo, maybe we could switch?

pip can also handle dependencies with a simple `pip install .` as it looks for the pyproject.toml

I guess uv is doing the same. With gdal we may need to mess around with conda anyway
